# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0116c46f105451572cfee064deebcb03b5f881fb0b81043afddffadd74c5256411680abfa5750c773078c46c002a697b23fcc819ff795e747530e3366d65936d

test:
  secret_key_base: 8ec6cd26f0fb2ff8ba03d5e21d54b8c239e7eca9bc5cd73870ec3c051f23698d3dc635f9d3aab8b684bcd424e036fc1a7a37b817886d42b62c329b43058d7db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
